ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.var-naming]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.indent-error-flow]
[rule.empty-block]
[rule.superfluous-else]
[rule.modifies-parameter]
[rule.confusing-naming]
[rule.confusing-results]

# It generates unnecessary reports
#[rule.flag-parameter]

# Currently this makes too much noise, but should add it in
# and perhaps ignore it in a few files
#[rule.unused-parameter]
#  severity = "warning"
#[rule.deep-exit]
#  severity = "warning"


# Already checked by megacheck
# [rule.unreachable-code]

# Adding these will slow down the linter
# They are already provided by megacheck
# [rule.unexported-return]
# [rule.time-naming]
# [rule.errorf]

# Adding these will slow down the linter
# Not sure if they are already provided by megacheck
# [rule.var-declaration]
# [rule.context-keys-type]

[2020/10/14 13:14:18.570 +08:00] [INFO] [split_region.go:202] [splitRegions] [key=74800000000000002d5f72800000000ee6b280]
[2020/10/14 13:14:18.570 +08:00] [INFO] [split_region.go:202] [splitRegions] [key=74800000000000002d5f72800000001dcd6500]
[2020/10/14 13:14:18.570 +08:00] [INFO] [split_region.go:202] [splitRegions] [key=74800000000000002d5f72800000002cb41780]
